apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: eminent-staging
    tier: backend
  name: common

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eminent-staging
  name: eminent-staging-deploy
  namespace: common
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: eminent-staging
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eminent-staging
        release: r11082019
    spec:
      containers:
        - env:
            - name: G_CLOUD_KEYFILE
              value: /var/secrets/google/information.json
          volumeMounts:
            - mountPath: /var/secrets/google
              name: storage-vol
              readOnly: true
          envFrom:
            - configMapRef:
                name: eminent-staging-config
          image: gcr.io/bjp-saral/github.com/jarvisconsulting/eminent
          imagePullPolicy: Always
          name: eminent-staging-container
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 1024Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: redis
          image: redis:7.0.4
          imagePullPolicy: Always
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - envFrom:
            - configMapRef:
                name: eminent-staging-config
          args:
            - sidekiq
          command:
            - bundle
            - exec
          image: gcr.io/bjp-saral/github.com/jarvisconsulting/eminent
          imagePullPolicy: Always
          name: eminent-staging-sidekiq
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: storage-vol
          secret:
            secretName: common-storage-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
      nodeSelector:
        cloud.google.com/gke-nodepool: staging
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "staging"
          effect: "NoSchedule"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: eminent-staging
  name: eminent-staging-service
  namespace: common
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: eminent-staging
  sessionAffinity: None
  type: LoadBalancer

