default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_MAX_THREADS"] || 10 %>
  timeout: 5000

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || "" %>

test:
  <<: *default
  url: <%= (ENV["DATABASE_URL"] || "") + "_test" %>

production:
  url: <%= ENV["DATABASE_URL"] || "" %>

ccdms:
  <<: *default
  url: <%= ENV["CCDMS_DATABASE_URL"] || "" %>